dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    secure: Eh7RVDXvzqu/75hdr/sy/ZBfrB8Uaz2f3aSTLUJok1gwQC0VL+jdfsQ8Bd9IC4MViFWknuYArkb+4dQh6H7f8lrAz1KBlLSUjMCH6q8HbDvegUiF6FFiHND+cVJHRyAszntclhmnwGiJZ3At2gDzCsRIImblV3PVxcwVpd28ORyNNvGCAkvDgYIgdIELz8VZ/EUUXUmq1UGhgxaxMF7zb/bCLx1ud2ImEzk0a4j+NdTehKPCh8pclDiN6avaMA+y5/BVRAgvQCGwZKXTQv+n2Z/7ljZGgcOndnXra3aHtqP2Cluh9A4W7B23caq6mOOzI/FhmXs4JP6p5DZVDA8nfe0pkpQJtM7I1vXWq2JBJ6iHEzvgepL/E5R50pi+ai0jPUiQR2GXsX3y0r6tbbF0T2OktsDK4ih0h7RCBfS6q5V56gWToil/A2C2v9+OY3lLpY1Zc2XSBCm1oeqXxwtn1QE3LdCSBR470mTGY9Xd2RkU6Hj3QvllGhTQ90WamAOIhSW6Q5CpEjXPIxSM40Q8NWXQ1gxUd8FAe1t7SJ1jhlG9sqt1JNDWXxiKyCrGInB+xz9AH+lIR2rQFW8Ce2v7hatjI5FvmL46+7iiRNMenCr+043G+tNWo4UHCqHspSX35yGtgghEJZhmM0HlrKa5s1ASH7EJWbKB5xuOAe1pkIU=
