dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: ApcM9vZ8RjHf1YaD1qsIhikElm3EUEaXUgrMNaZfrBqJo0IOdq8R9ZIpDxOVR3sx+3ivBraTnkgiljqwiqPmZzZJjjii2tZvuEYe0n4W0NjhcwPHexIZZgVUdFWxCS8uheBPR7/I5mcLy1+f4S/yoUt6eNg3yzidud1VyqSudkArDzy1Ej8G7vUvQlOjwRWW7bNpZETBPVZ7oQIcJ/6xjufqPyO2vnjNPqh2E7o/WqeeFSXe6qYGld6zwFKrhwUiXP7SSeLyJYl5Y5jNhcWViLf6UbrVFlxLhO2zx4wS5PRoK6h+oeOAmexYmtGgDdKnw7Cm24/ujtanUS65x2wGbZLKT0zLVB3yjzcpyAx7rLYsgjq73AkYPc12hk9ivcHhjO9h2zkB94HYtKWUV8zrLn5MSE/sdcIVi0iFCQHZ6fPmpjCzD69Sjm5QKWKwIK3Q14pPvBoshXv1MbQDVL/8yxdAXN8BEZb/57VvMyPaKGx+OQsLgAW0j2Y2gJ5M0mM9XIITs4MvrFa4ZHvd+NhJ+TZ4GzglvSiO19fVNZsrlVTPLOgpIG4LKggx7gr6ZxjLPLAreRXjhTT65QHhBr1ZFgqrfX24IjyXy2cIxQZuhPq6rZzvGuHsNbCPkh+w//USKSS3Id+76PE1YiettGxw6yZrX+Mavg6xiEbQHLJZT+4=
