FROM alpine:3.9.4

ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

COPY . $APP_HOME

RUN apk add --no-cache ruby-full=2.5.5-r0

RUN apk add --no-cache --virtual ruby-dev-deps \
        ruby-dev=2.5.5-r0 \
        build-base=0.5-r1 && \
    gem install bundler:1.17.2 --no-ri --no-rdoc && \
    bundle install --no-cache --quiet && \
    apk del ruby-dev-deps

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

CMD ["puma"]
