version: '3.3'
services:
  db:
    image: mongo:${MONGO_DB_VERSION}
    volumes:
      - db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
      prometheus:
  ui:
    image: ${USER_NAME}/ui:${UI_SERVICE_VERSION}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - front_net
      - prometheus
    environment:
      POST_SERVICE_HOST: post
      COMMENT_SERVICE_HOST: comment
  post:
    image: ${USER_NAME}/post:${POST_SERVICE_VERSION}
    networks:
      - back_net
      - front_net
      - prometheus
    environment:
      POST_DATABASE_HOST: post_db
  comment:
    image: ${USER_NAME}/comment:${COMMENT_SERVICE_VERSION}
    networks:
      - back_net
      - front_net
      - prometheus
    environment:
      COMMENT_DATABASE_HOST: comment_db

volumes:
  db:

networks:
  front_net:
  back_net:
  prometheus:
