---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: comment-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reddit
      component: comment
  template:
    metadata:
      name: comment-pod
      labels:
        app: reddit
        component: comment
    spec:
      containers:
      - image: pavelpuchok/comment
        name: comment
        env:
          - name: COMMENT_DATABASE_HOST
            value: comment-db
